/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(modes)'}${'/(animated)'}/convert` | `/convert`; params?: Router.UnknownInputParams; } | { pathname: `${'/(modes)'}${'/(animated)'}/upload` | `/upload`; params?: Router.UnknownInputParams; } | { pathname: `${'/(modes)'}${'/(audiolized)'}/generate` | `/generate`; params?: Router.UnknownInputParams; } | { pathname: `${'/(modes)'}${'/(audiolized)'}/upload` | `/upload`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/about` | `/about`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(modes)'}${'/(animated)'}/convert` | `/convert`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(modes)'}${'/(animated)'}/upload` | `/upload`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(modes)'}${'/(audiolized)'}/generate` | `/generate`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(modes)'}${'/(audiolized)'}/upload` | `/upload`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/about` | `/about`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(modes)'}${'/(animated)'}/convert${`?${string}` | `#${string}` | ''}` | `/convert${`?${string}` | `#${string}` | ''}` | `${'/(modes)'}${'/(animated)'}/upload${`?${string}` | `#${string}` | ''}` | `/upload${`?${string}` | `#${string}` | ''}` | `${'/(modes)'}${'/(audiolized)'}/generate${`?${string}` | `#${string}` | ''}` | `/generate${`?${string}` | `#${string}` | ''}` | `${'/(modes)'}${'/(audiolized)'}/upload${`?${string}` | `#${string}` | ''}` | `/upload${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/about${`?${string}` | `#${string}` | ''}` | `/about${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(modes)'}${'/(animated)'}/convert` | `/convert`; params?: Router.UnknownInputParams; } | { pathname: `${'/(modes)'}${'/(animated)'}/upload` | `/upload`; params?: Router.UnknownInputParams; } | { pathname: `${'/(modes)'}${'/(audiolized)'}/generate` | `/generate`; params?: Router.UnknownInputParams; } | { pathname: `${'/(modes)'}${'/(audiolized)'}/upload` | `/upload`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/about` | `/about`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | `/+not-found${`?${string}` | `#${string}` | ''}` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
