name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Test SSH Connection (debug)
        run: |
          ssh -vvv ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} echo "SSH connected"
        

      - name: SSH & Deploy
        run: |
          ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            cd ~/mosslab-app/apps/backend
            git pull origin main
            pnpm install
            pnpm build
            pm2 start dist/main.js --name mosslab-backend || pm2 restart mosslab-backend
          EOF
